### ISSUE TITLE
Complemento pago

### ISSUE THREAD

**Issue by mparamo31** [GrupoCorasa/cfdi-base#22]
Buena noche, anteriormente en la versión 3.3 para genear el complemento pago usaba esta forma CFDv33 cfd = new CFDv33(Comprobante,"mx.bigdata.sat.common.pagos.schema"); pero en la versión 4.0 no se que usar, si solo pongo el comprobante me manda error, me podría auxiliar.
java.lang.ClassNotFoundException: com.google.common.reflect.ClassPath
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mx.grupocorasa.sat.common.CfdCommon.defineComprobanteContext(CfdCommon.java:150)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.getComprobanteContexts(CFDv40.java:150)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.getContext(CFDv40.java:157)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.<init>(CFDv40.java:76)

Saludos

**Comment by hortegag91** [comment]
Hay una clase con los [tests de la versión 4.0](https://github.com/GrupoCorasa/cfdi-base/blob/main/src/test/java/mx/grupocorasa/sat/cfdi/v4/CFDv40Test.java)
Ahi podrás ver ejemplos completos sobre como hay que generarlos. Por ahi de la línea 151 estan los tests de los complementos de pago.
Si tienes alguna duda, reabres el issue por favor.
