### ISSUE TITLE
Comprobante de pago

### ISSUE THREAD

**Issue by mparamo31** [GrupoCorasa/cfdi-base#23]
Buena tarde.
Antes que nada muchas gracias por contestar mi duda sobre el complemento de pago que hice llegar hace aproxidamente una semana, seguí lo que me compartió, copié tal cual el código en mi proyecto y me mandó el error que ya le había compartido anteriormente en la línea 

CFDv40 cfd = new CFDv40(comprobante);

Al llegar a esta instrucción lanza la siguiente excepción
java.lang.ClassNotFoundException: com.google.common.reflect.ClassPath
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mx.grupocorasa.sat.common.CfdCommon.defineComprobanteContext(CfdCommon.java:150)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.getComprobanteContexts(CFDv40.java:150)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.getContext(CFDv40.java:157)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.<init>(CFDv40.java:76)

**Comment by hortegag91** [comment]
Buen día,
Normalmente estos problemas son por un conflicto de las dependencias
Lo más común sería generar el arbol de dependencias (tanto gradle como maven manejan ya un task para esto) y verificar donde está entrando en conflicto las distintas versiones.
Si pudieran poner el arbol de dependencias de su proyecto final para continuar apoyandolos.
