### ISSUE TITLE
Actualizacion a Java 17

### ISSUE THREAD

**Issue by luisgithub** [GrupoCorasa/cfdi-base#30]
Hola, tienen planes en actualizar la el componente para que soporte java 17, estoy probando con spring boot 3 y al momento de crear el objeto CFDv40 en el log obtengo el siguiente error:

java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at mx.grupocorasa.sat.cfdi.v4.CFDv4.<init>(CFDv4.java:11) ~[cfdi-base-4.0.13.jar:na]
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.<init>(CFDv40.java:72) ~[cfdi-base-4.0.13.jar:na]

**Comment by jalgaba** [comment]
Hola, eso no parece un problema de java 17, mas bien que te falta resolver las dependencias indicadas en [cfdi-base-4.0.14.pom](https://github.com/GrupoCorasa/cfdi-base/packages/1120118)  especificamente *com.google.guava*

**Comment by luisgithub** [comment]
Gracias por responder, de hecho ya resolví el issue y migre exitosamente la
librería a spring boot 3 con Java 17
