### ISSUE TITLE
Ayuda Pago 2.0

### ISSUE THREAD

**Issue by JCTOTTI10** [GrupoCorasa/cfdi-base#31]
**Hola para procesar un pago 2.0, me marca el siguiente error:** 

StandardWrapperValve[dispatcher]: Servlet.service() for servlet dispatcher threw exception
java.lang.NoSuchMethodError: com.google.common.collect.Sets.newLinkedHashSetWithExpectedSize(I)Ljava/util/LinkedHashSet;
	at com.google.common.collect.MultimapBuilder$LinkedHashSetSupplier.get(MultimapBuilder.java:241)
	at com.google.common.collect.MultimapBuilder$LinkedHashSetSupplier.get(MultimapBuilder.java:232)
	at com.google.common.collect.Multimaps$CustomSetMultimap.createCollection(Multimaps.java:265)
	at com.google.common.collect.AbstractSetMultimap.createCollection(AbstractSetMultimap.java:1)
	at com.google.common.collect.AbstractMultimap.createCollection(AbstractMultimap.java:155)
	at com.google.common.collect.AbstractMultimap.get(AbstractMultimap.java:339)
	at com.google.common.collect.AbstractSetMultimap.get(AbstractSetMultimap.java:50)
	at com.google.common.reflect.ClassPath$DefaultScanner.scanJarFile(ClassPath.java:482)
	at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:385)
	at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:369)
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:352)
	at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:339)
	at com.google.common.reflect.ClassPath.from(ClassPath.java:104)
	at mx.grupocorasa.sat.common.CfdCommon.defineComprobanteContext(CfdCommon.java:150)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.getComprobanteContexts(CFDv40.java:148)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.getContext(CFDv40.java:167)
	at mx.grupocorasa.sat.cfdi.v4.CFDv40.<init>(CFDv40.java:73)
	at controller.servlet.PagoFacturaController.handleRequestInternal(PagoFacturaController.java:238)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:936)

**mi instancia del CFDI**

CFDv40 cfd =new CFDv40(com,"mx.grupocorasa.sat.common.Pagos20");

**mis librerias son las siguientes:**

![image](https://user-images.githubusercontent.com/84634040/228049262-a0c4e58f-69ad-4fb4-9798-71aec7308eff.png)
![image](https://user-images.githubusercontent.com/84634040/228049341-1a0bb3a9-4c99-4cfb-ad02-df84a446f7ad.png)
![image](https://user-images.githubusercontent.com/84634040/228049491-8b896fff-d97f-465e-be2c-a9a5f1c8a20c.png)

alguna idea de que estoy haciendo mal ?

**Comment by hortegag91** [comment]
Te recomiendo generar el arbol de dependencias de maven/gradle para ver donde podría estar el problema.  Por el error me imagino que es una incompatibilidad entre versiones, GSON supondría, tengo entendido que es de Google

**Comment by hortegag91** [comment]
Revisando la clase del error, es GUAVA donde estas teniendo problemas. Verifica porque no te lo está poniendo, ya que no lo veo en las imagenes que enviaste
![image](https://user-images.githubusercontent.com/14035835/228061586-7f0f29e8-e735-40fa-bbfd-bf9556d724f7.png)

**Comment by JCTOTTI10** [comment]
Tienes razon no envie esa parte pero si tengo **Guava-23.0**

**Comment by JCTOTTI10** [comment]
será la version q uso de Guava ?

**Comment by hortegag91** [comment]
Me atrevería a suponer que si, el proyecto cfdi utiliza la versión 31.0.1, deben haber métodos que la versión 23 no tienen. Intenta actualizar la dependencia y debería funcionar.

**Comment by JCTOTTI10** [comment]
ok, lo mas raro es q para todos los demas comprobantes funciona correctamente solo en el complemento de Pago es donde me marca este error

**Comment by hortegag91** [comment]
Supongo que debe ser algún método muy específico que solo utilizan los pagos, pero según el error, ese es el problema, definitivo, comentas y cierras si quedó resuelto al actualizar la libreria de Guava

**Comment by JCTOTTI10** [comment]
**Actualize lal ibreria y ahora sale este error:**

![image](https://user-images.githubusercontent.com/84634040/228082285-93ba7d26-8639-46b6-879d-e03c1cc02ed1.png)

**Comment by hortegag91** [comment]
Sigue marcando el error de que no está el método (casi siempre es por conflicto en librerias). Tu proyecto lo tienes en maven o gradle?

**Comment by JCTOTTI10** [comment]
es un proyecto en ANT

**Comment by hortegag91** [comment]
Intenta imprimir el arbol de dependencias y pasarlo porfa
https://ant.apache.org/ivy/history/2.4.0/use/dependencytree.html

**Comment by JCTOTTI10** [comment]
ok lo elaboro

**Comment by JCTOTTI10** [comment]
**listo la libreria q me estaba haciendo el problema era**

![image](https://user-images.githubusercontent.com/84634040/228376851-d8923e27-1f17-469a-9732-b9651d883d7e.png)

**muchas gracias por la ayuda**
