### ISSUE TITLE
Error al sellar comprobante

### ISSUE THREAD

**Issue by juanfra0064** [GrupoCorasa/cfdi-base#8]
Hola que tal, al tratar de sellar el comprobante se genera este error.

Codigo:
Comprobante compStamped compStamped = cfd33.sellarComprobante(privateKey.getKey(), certificate.getKey());

Error:
java.lang.IllegalArgumentException: No soportado: http://javax.xml.XMLConstants/property/accessExternalDTD

**Comment by hortegag91** [comment]
Podrías proporcionar el stacktrace completo, pareciera ser algún conflico entre librerías.

**Comment by juanfra0064** [comment]
Hola, este es el stacktrace completo

Te lo agradeceria mucho por que tengo que implementar los cambios antes del 1 de enero

Gracias!
PD: Y de pasadita te llega de navidad una botellita!

dic 20, 2021 12:15:34 PM com.softjua.propsbs.bill.Bill stamping
GRAVE: null
java.lang.IllegalArgumentException: No soportado: http://javax.xml.XMLConstants/property/accessExternalDTD
	at org.apache.xalan.processor.TransformerFactoryImpl.setAttribute(TransformerFactoryImpl.java:485)
	at mx.grupocorasa.sat.common.CfdCommon.getOriginalBytes(CfdCommon.java:224)
	at mx.grupocorasa.sat.common.CfdCommon.getSignature(CfdCommon.java:235)
	at mx.grupocorasa.sat.cfdi.CFDv33.sellar(CFDv33.java:142)
	at mx.grupocorasa.sat.cfdi.CFDv33.sellarComprobante(CFDv33.java:173)
	at com.softjua.propsbs.bill.Bill.stamping(Bill.java:915)
	at com.softjua.propsbs.bill.Bill.stamping(Bill.java:815)
	at com.softjua.propsbs.bill.Bill.billing(Bill.java:412)
	at com.softjua.propsbs.sale.Sale.makePayment(Sale.java:391)
	at com.softjua.propsbs.sale.Sale.onFirm(Sale.java:458)
	at com.softjua.propsbs.sale.Sale.lambda$onFirm$7(Sale.java:421)
	at com.softjua.propsbs.em.SecureEm.commitBlock(SecureEm.java:180)
	at com.softjua.propsbs.sale.Sale.onFirm(Sale.java:420)
	at com.softjua.bspos.sale.SaleUI.acceptAction(SaleUI.java:208)
	at com.softjua.bspos.operation.OperationUI$2.actionPerformed(OperationUI.java:205)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

BUILD STOPPED (total time: 1 minute 50 seconds)

**Comment by hortegag91** [comment]
Parece que se puede solucionar quitando estas líneas de código en la instancia del TransformerFactory
```java
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "");
factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_STYLESHEET, "");
```
Intentaré subir una nueva versión con estos cambios lo antes posible.

**Comment by juanfra0064** [comment]
Gracias!

**Comment by juanfra0064** [comment]
Hola que tal, Alguna novedad!?

Te lo agradeceria mucho!!!

**Comment by hortegag91** [comment]
Acabo de subir la primer versión que incluye el CFDi 4.0 (aún sin tests, por lo que podría ser inestable para el 4.0).
Esta versión ya tiene los cambios marcados aqui.
Espero te sirva, si fue asi, cierras el issue por favor.

https://github.com/GrupoCorasa/cfdi-base/packages/1120118

**Comment by juanfra0064** [comment]
Listo parece ya quedo, hice una prueba y la genero, igual voy a seguir haciendo pruebas para implementar lo de carta prote

Gracias!!!

PD: Si era en serio lo de la botellita, de cual quieres? y a donde la mando? o bien dime y te transfiero para que tu te la compres!

**Comment by hortegag91** [comment]
Tírame un mensajito de whatsapp si quieres y nos ponemos de acuerdo 662 183 1587 :smiley:
